const fs = require('fs');
const path = require('path');
const crypto = require('crypto');
const { ethers } = require('ethers');
const { createVM } = require('@ethereumjs/vm');
const { createAddressFromString, hexToBytes, Account } = require('@ethereumjs/util');

const ROOT = path.join(__dirname, '..');
const OUT = path.join(ROOT, 'release/BROCODE-art-only-preview.html');

(async () => {
  const artifact = JSON.parse(fs.readFileSync(path.join(ROOT, 'build/BroCodeBros2121.artifact.json'), 'utf8'));
  const vm = await createVM();
  const caller = createAddressFromString('0xef5c5b9129aafefdff459349e7628c60016e810e');
  await vm.stateManager.putAccount(caller, new Account(0n, ethers.parseEther('100')));
  const iface = new ethers.Interface(artifact.abi);
  const deployment = await vm.evm.runCall({
    caller,
    data: hexToBytes(artifact.bytecode + iface.encodeDeploy([caller.toString()]).slice(2)),
    gasLimit: 30_000_000n
  });
  if (deployment.execResult.exceptionError) throw deployment.execResult.exceptionError;

  const ids = Array.from({ length: 2121 }, (_, i) => i + 1);
  const svgs = new Map();
  for (const id of ids) {
    const result = await vm.evm.runCall({
      caller,
      to: deployment.createdAddress,
      data: hexToBytes(iface.encodeFunctionData('previewSVG', [id])),
      gasLimit: 2_000_000n
    });
    if (result.execResult.exceptionError) throw new Error(`previewSVG(${id}) failed: ${result.execResult.exceptionError}`);
    svgs.set(id, iface.decodeFunctionResult('previewSVG', result.execResult.returnValue)[0]);
  }

  // Shuffle only the presentation order; no token ID or rarity label is emitted into the page.
  let state = BigInt('0x' + crypto.createHash('sha256').update('BROCODE-art-only-gallery-order-v1').digest('hex'));
  function randomIndex(max) {
    state = (state * 6364136223846793005n + 1442695040888963407n) & ((1n << 64n) - 1n);
    return Number(state % BigInt(max));
  }
  for (let i = ids.length - 1; i > 0; i--) {
    const j = randomIndex(i + 1);
    [ids[i], ids[j]] = [ids[j], ids[i]];
  }

  const cards = ids.map(id => `<figure><img loading="lazy" alt="BRO CODE avatar art preview" src="data:image/svg+xml;charset=utf-8,${encodeURIComponent(svgs.get(id))}"></figure>`).join('\n');
  const html = `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>BRO CODE — art-only collection preview</title>
<style>
:root{color-scheme:dark;--blue:#075cff;--navy:#061137;--ink:#eaf0ff}
*{box-sizing:border-box}
body{margin:0;background:radial-gradient(circle at 50% 0%,#123277 0,#07112e 42rem,#050a1d 100%);color:var(--ink);font:15px/1.5 system-ui,-apple-system,Segoe UI,sans-serif}
header{position:sticky;top:0;z-index:1;padding:1rem clamp(1rem,4vw,3rem);background:#061137ee;border-bottom:1px solid #3977ff55;backdrop-filter:blur(10px)}
h1{font-size:clamp(1.2rem,2.7vw,2rem);margin:0 0 .25rem;letter-spacing:.04em}
header p{margin:0;color:#bdcaff}
.grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(112px,1fr));gap:12px;padding:16px;max-width:1600px;margin:auto}
figure{margin:0;aspect-ratio:1;background:#07112e;border:1px solid #2761cf;border-radius:12px;overflow:hidden;box-shadow:0 5px 18px #0005}
img{display:block;width:100%;height:100%;object-fit:contain;image-rendering:pixelated}
footer{text-align:center;padding:1.5rem;color:#a8b9e8;font-size:.85rem}
</style>
</head>
<body>
<header><h1>$BROS · BRO CODE</h1><p>Art-only preview of all 2,121 deterministic on-chain SVG avatars. Token IDs, trait names, and rarity labels are intentionally omitted from the display.</p></header>
<main class="grid">${cards}</main>
<footer>Local approval preview only · Metadata and SVG are generated by the same contract build. On-chain IDs and trait assignments remain publicly derivable from the deterministic seed and bytecode.</footer>
</body>
</html>`;
  fs.writeFileSync(OUT, html);
  console.log(`Wrote ${OUT} (${(Buffer.byteLength(html) / 1024 / 1024).toFixed(2)} MiB; ${ids.length} art-only cards)`);
})().catch(err => { console.error(err); process.exit(1); });
